batch_size: 4
length: 384
epochs: 101
steps_per_epoch: 128

print_frequency: 10
save_frequency: 10

samples_dir: './samples'
weights_dir: './checkpoints'

learning_rate: 0.0001
checkpoints: True

noDecom: False